name: Deploy manually
run-name: Deploy of ${{ inputs.tag }} manually
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag to deploy'
                required: true
                type: string

jobs:
    deploy:
        uses: ./.github/workflows/deploy_tag.yml
        with:
            tag: ${{ inputs.tag }}
